# kindly generated by appropriated Rails generator
Mailjet.configure do |config|
  config.api_key = '562c8de551bdeb631b75d17387285411'
  config.secret_key = 'bc730a6f03799b5362c37e6ea3259aa4'
  config.default_from = 'contact@alt-r.fr'
  # Mailjet API v3.1 is at the moment limited to Send API.
  # We’ve not set the version to it directly since there is no other endpoint in that version.
  # We recommend you create a dedicated instance of the wrapper set with it to send your emails.
  # If you're only using the gem to send emails, then you can safely set it to this version.
  # Otherwise, you can remove the dedicated line into config/initializers/mailjet.rb.
  config.api_version = 'v3.1'
end
